### ISSUE TITLE
Add year to WPILib icon

### ISSUE THREAD

**Issue by cyocom** [wpilibsuite/WPILibInstaller-Avalonia#201]
**Is your feature request related to a problem? Please describe.**
Since the WPILib suite does not override the previous year's installation (for good reason), having multiple years of the WPILib suite installed is relatively common.
When used in this configuration, it can often be confusing to determine which tools you are using are from which year's installation.

**Describe the solution you'd like**
My suggestion is to add the year in a clear way to the icons so it is evident which version of which applications/tools you are using.

**Describe alternatives you've considered**
Changing the name on the tools themselves would be probably be more confusing then just changing the icon, but it is also an option.

**Additional context**
n/a

**Comment by calcmogul** [comment]
The shortcut name already includes the year though.

**Comment by sciencewhiz** [comment]
The shortcut name for vs code has the year, but the tools don't. The tools are in a folder with the shortcut name, so if you browse the start menu or desktop, you'll get it. However, if you search the start menu (which is what I do most of the time, because it's faster) then you'll see multiple copies of the tools without any indication of the year.

![image](https://user-images.githubusercontent.com/4885091/142036013-7aa732d8-c2f6-4894-ac73-bfea93169ea8.png)
