### ISSUE TITLE
Add custom install option

### ISSUE THREAD

**Issue by lhvy** [wpilibsuite/WPILibInstaller-Avalonia#228]
### Suggestion
Add an install option other than "Tools" and "Everything" that allows the user to pick individual elements to install.

### Justification
I just installed WPILib 2022.1.1 beta 4 and was greeted with the new install options, Tools and Everything. Personally, I feel as though the old method of selecting individual elements worked better as I wanted to install some elements located in both the tools and everything sections, but I didn't want to install literally everything like I have to do now in order to get certain things.

**Comment by ThadHouse** [comment]
The old custom options never actually worked right. The only one you could safely remove without breaking something was the c++ compiler. All the other things if disabled would break something in the background. And the compiler is only 90 mb, so it really doesn't gain anything to add an option we have to debug and test.

Which options did you want to disable anyway?

**Comment by lhvy** [comment]
I was typically disabling c++ compiler, JDK and Gradle. JDK seems to add about 230 MB of overhead and Gradle is adding 115 MB, JDK I have a system wide installation and our team's Gradle version typically doesn't match the one offered by the installer.

**Comment by ThadHouse** [comment]
Jdk we don't support using the system wide jdk, so that option will never return. 

As for gradle, gradlerio only supports the version of gradle we ship with. Using alternate versions can and does break. So skipping that isn't valid for our use cases either.

The C++ compiler is that actually just plain isn't used by Java teams, but it's not worth taking the extra dev time, especially because it really doesn't take up that much space.

**Comment by lhvy** [comment]
Hm ok, I seem to be able to run fine with my JDK installation and even changing the Gradle version (never a major version, at most something like 6.1 --> 6.3)

Sounds like too much effort for a minor change, thanks for the quick responses! I'll close the issue now.

**Comment by ThadHouse** [comment]
I can add some documentation on what folders after install are safe to remove if you need to free disk space. But I'd prefer to add that rather then the old options back.

And yes a system jdk generally works, but we want to make sure generally our selected version is used, because we've seen small updates break things before.

As for gradle, in Java it's less of an issue, but c++ breaks even with minor version bumps. Pretty much always. And we are upgrading to 7.3.3 for the season. We were only a year behind because 2021 was a fully compatible release.

**Comment by lhvy** [comment]
> I can add some documentation on what folders after install are safe to remove if you need to free disk space

Instructions would be awesome if you have the time!

Thanks for the info, I'll keep in mind what you said about JDK and Gradle versions.
